services:
  sgq-cag-llm:
    container_name: sgq-cag-llm
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "80:8000"
    tmpfs:
      - /tmp:size=2G
