services:
  sgq-cag-llm:
    container_name: sgq-cag-llm
    build: ./src
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "80:8000"
    tmpfs:
      - /tmp:size=1g
